// AUTO-GENERATED by scripts/compile.mjs — do not edit by hand.
export const feedbackAbi = [
  {
    "inputs": [
      {
        "internalType": "string[]",
        "name": "initialCourses",
        "type": "string[]"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadySubmitted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CourseInactive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidCourse",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "value",
        "type": "uint8"
      }
    ],
    "name": "InvalidRating",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TextTooLong",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "courseId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "name": "CourseAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "courseId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      }
    ],
    "name": "CourseStatusChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "feedbackId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "courseId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "submitter",
        "type": "address"
      }
    ],
    "name": "FeedbackSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_NAME_LENGTH",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_TEXT_LENGTH",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "RATING_COUNT",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "name": "addCourse",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "courseCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feedbackCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCourses",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          }
        ],
        "internalType": "struct WorkshopFeedback.Course[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "feedbackId",
        "type": "uint256"
      }
    ],
    "name": "getFeedback",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "submitter",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "timestamp",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "courseId",
            "type": "uint32"
          },
          {
            "internalType": "enum WorkshopFeedback.Reason",
            "name": "reason",
            "type": "uint8"
          },
          {
            "internalType": "enum WorkshopFeedback.Recommend",
            "name": "recommend",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "wouldPay",
            "type": "bool"
          },
          {
            "internalType": "uint8[30]",
            "name": "ratings",
            "type": "uint8[30]"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "mostUseful",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "improvements",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "complaints",
            "type": "string"
          }
        ],
        "internalType": "struct WorkshopFeedback.Feedback",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "limit",
        "type": "uint256"
      }
    ],
    "name": "getFeedbacks",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "submitter",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "timestamp",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "courseId",
            "type": "uint32"
          },
          {
            "internalType": "enum WorkshopFeedback.Reason",
            "name": "reason",
            "type": "uint8"
          },
          {
            "internalType": "enum WorkshopFeedback.Recommend",
            "name": "recommend",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "wouldPay",
            "type": "bool"
          },
          {
            "internalType": "uint8[30]",
            "name": "ratings",
            "type": "uint8[30]"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "mostUseful",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "improvements",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "complaints",
            "type": "string"
          }
        ],
        "internalType": "struct WorkshopFeedback.Feedback[]",
        "name": "page",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "hasSubmitted",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "courseId",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      }
    ],
    "name": "setCourseActive",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "uint32",
            "name": "courseId",
            "type": "uint32"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "uint8[30]",
            "name": "ratings",
            "type": "uint8[30]"
          },
          {
            "internalType": "string",
            "name": "mostUseful",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "improvements",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "complaints",
            "type": "string"
          },
          {
            "internalType": "enum WorkshopFeedback.Reason",
            "name": "reason",
            "type": "uint8"
          },
          {
            "internalType": "enum WorkshopFeedback.Recommend",
            "name": "recommend",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "wouldPay",
            "type": "bool"
          }
        ],
        "internalType": "struct WorkshopFeedback.FeedbackInput",
        "name": "input",
        "type": "tuple"
      }
    ],
    "name": "submitFeedback",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "feedbackId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const
