// Compiles contracts/WorkshopFeedback.sol with solc-js and writes:
//   artifacts/WorkshopFeedback.json  (abi + bytecode, used by deploy script)
//   src/contract/abi.ts              (typed ABI for the React app)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import solc from 'solc'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourcePath = resolve(root, 'contracts/WorkshopFeedback.sol')

const input = {
  language: 'Solidity',
  sources: { 'WorkshopFeedback.sol': { content: readFileSync(sourcePath, 'utf8') } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    viaIR: true,
    evmVersion: 'shanghai',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
}

const output = JSON.parse(solc.compile(JSON.stringify(input)))
const errors = (output.errors ?? []).filter((e) => e.severity === 'error')
for (const e of output.errors ?? []) console[e.severity === 'error' ? 'error' : 'warn'](e.formattedMessage)
if (errors.length) process.exit(1)

const c = output.contracts['WorkshopFeedback.sol'].WorkshopFeedback
const artifact = { contractName: 'WorkshopFeedback', abi: c.abi, bytecode: '0x' + c.evm.bytecode.object }

mkdirSync(resolve(root, 'artifacts'), { recursive: true })
writeFileSync(resolve(root, 'artifacts/WorkshopFeedback.json'), JSON.stringify(artifact, null, 2))

mkdirSync(resolve(root, 'src/contract'), { recursive: true })
writeFileSync(
  resolve(root, 'src/contract/abi.ts'),
  `// AUTO-GENERATED by scripts/compile.mjs — do not edit by hand.\nexport const feedbackAbi = ${JSON.stringify(c.abi, null, 2)} as const\n`,
)

console.log(`Compiled WorkshopFeedback (solc ${solc.version()}) → artifacts/ and src/contract/abi.ts`)
